### ISSUE TITLE
Uncaught TypeError: Cannot read property 'string' of undefined

### ISSUE THREAD

**Issue by davthu** [hichroma/learnstorybook.com#4]
Just followed the first step on the tutorial at https://www.learnstorybook.com/get-started/ and when opening the storybook at http://localhost:6006/ an **Uncaught TypeError** error is thrown and the page is blank.

```
{
  "name": "tasklist",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^16.3.1",
    "react-dom": "^16.3.1",
    "react-scripts": "1.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
    "storybook": "start-storybook -p 6006",
    "build-storybook": "build-storybook"
  },
  "devDependencies": {
    "@kadira/storybook": "^2.21.0"
  }
}
```

**Comment by domyen** [comment]
@davthu Fixed. Try deleting the folder and following the steps again 🙏

**Comment by davthu** [comment]
I'm sorry but it didn't help to remove the tasklist folder and start again. Instead I installed Storybook as recommended on their site using  `npm i -g @storybook/cli` and skipping the yarn part and then it works. This time package.json looks like this:

```
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^16.3.1",
    "react-dom": "^16.3.1",
    "react-scripts": "1.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
    "storybook": "start-storybook -p 9009 -s public",
    "build-storybook": "build-storybook -s public"
  },
  "devDependencies": {
    "@storybook/react": "^3.4.0",
    "@storybook/addon-actions": "^3.4.0",
    "@storybook/addon-links": "^3.4.0",
    "@storybook/addons": "^3.4.0",
    "babel-core": "^6.26.0",
    "babel-runtime": "^6.26.0"
  }
}
```

**Comment by tmeasday** [comment]
FTR, I think the best way to use one-shot tools like `getstorybook` and `create-react-app` is via `npx`---it will always install the latest version (rather than whatever you have installed on your system from last time you used it), and ensure you are up to date. @domyen should we change this part?

**Comment by domyen** [comment]
@tmeasday do it!

**Comment by tmeasday** [comment]
https://github.com/hichroma/learnstorybook.com/commit/99bfe6a106fb30b2e687d94d13ed245114810218
