### ISSUE TITLE
How to translate?

### ISSUE THREAD

**Issue by icarlossz** [hichroma/learnstorybook.com#5]
Hello, I would like to help with the translation of the tutorial into Spanish but would like an explanation on how to do it in the same way it can be useful for anyone who also intends to help translate.

Greetings,
Carlos

**Comment by domyen** [comment]
Great question Carlos. The translation initiative is new so we're building a process out right now. Here's what I'm thinking:

**For contributors**

1. Fork
2. Add a new directory in content with language (e.g., `/content/spanish`).
3. Copy the existing docs to the new directory
4. Translate markdown content including what's in the "frontmatter" (title, tocTitle, description), but leave the code, commit, and filename
5. Run the project using `yarn develop` to confirm that everything looks OK. For now, you can preview changes by going to a url that looks like this `http://localhost:8000/spanish/composite-component`
6. Make a pull request

**Todo from a development perspective** (me or @tmeasday)
Contributors can start translating now by doing the above. But the sidebar and links won't work till we sort out the following features:

- Support languages in the `/content` directory (e.g., `/content/spanish`, `/content/english`).
- Add a language picker 
- Ensure the sidebar works with new languages

**Comment by domyen** [comment]
Updated #3 to reflect the steps to get started.

**Comment by domyen** [comment]
Going to close this and open up a Spanish translation issue where we can chat further
